package com.crm.travelcrm.booking.mapper;

import com.crm.travelcrm.booking.assignment.BookingAssigneeView;
import com.crm.travelcrm.booking.dto.request.CreateBookingRequestDTO;
import com.crm.travelcrm.booking.dto.request.UpdateBookingRequestDTO;
import com.crm.travelcrm.booking.dto.response.BookingResponseDTO;
import com.crm.travelcrm.booking.dto.response.BookingSummaryDTO;
import com.crm.travelcrm.booking.entity.Booking;
import org.mapstruct.*;


@Mapper(
        componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        // If a destination field has no source, fail at compile time — not silently
        unmappedTargetPolicy = ReportingPolicy.ERROR
)
public interface BookingMapper {

    // ── CreateBookingRequestDTO → Booking ─────────────────────────────────────
    //
    // Rule: mapper only maps what the CLIENT sends.
    // Everything the SERVER owns is ignored here and set by the service.
    // This makes it impossible to accidentally trust client-supplied values
    // for server-owned fields like tenantId, bookingCode, netProfit.

    @Mapping(target = "id",                     ignore = true)
    @Mapping(target = "publicId",               ignore = true)
    @Mapping(target = "tenantId",               ignore = true)  // set by service from JWT
    @Mapping(target = "bookingCode",            ignore = true)  // generated by service
    @Mapping(target = "customerNameSnapshot",   ignore = true)  // resolved by service
    @Mapping(target = "destinationId",          ignore = true)  // resolved by service
    @Mapping(target = "destinationSnapshot",    ignore = true)  // resolved by service
    @Mapping(target = "sourceLeadPublicId",     ignore = true)  // set by conversion flow only
    @Mapping(target = "sourceQuotationPublicId", ignore = true) // set by conversion flow only
    @Mapping(target = "cancellationPolicyPublicId", ignore = true) // resolved + pinned by service
    @Mapping(target = "cancellationPolicyVersion",  ignore = true) // resolved + pinned by service
    @Mapping(target = "gst",                    ignore = true)  // calculated by service
    @Mapping(target = "tcs",                    ignore = true)  // calculated by service
    @Mapping(target = "totalPayable",           ignore = true)  // calculated by service
    @Mapping(target = "totalInternalCosts",     ignore = true)  // summed from the expense ledger
    @Mapping(target = "totalVendorCosts",       ignore = true)  // summed from the expense ledger
    @Mapping(target = "netProfit",              ignore = true)  // calculated by BookingProfitService
    // The DTO carries a vendor publicId; the entity carries publicId + a name snapshot. Both are set
    // by the service after a tenant-scoped lookup — a client must never be able to name a vendor the
    // master does not agree with. Ignored here so MapStruct does not wire the id through unvalidated.
    @Mapping(target = "vendorPublicId",         ignore = true)  // resolved + validated by service
    @Mapping(target = "vendorName",             ignore = true)  // snapshotted by service
    @Mapping(target = "paidAmount",             ignore = true)  // starts at 0
    @Mapping(target = "refundedAmount",         ignore = true)  // starts at 0; owned by the refund flow
    @Mapping(target = "status",                 ignore = true)  // starts as PENDING
    @Mapping(target = "paymentStatus",          ignore = true)  // starts as UNPAID
    @Mapping(target = "services",               ignore = true)  // mapped separately below
    @Mapping(target = "createdBy",              ignore = true)  // set by @CreatedBy auditing
    @Mapping(target = "updatedBy",              ignore = true)  // set by @LastModifiedBy
    @Mapping(target = "createdAt",              ignore = true)  // set by @CreationTimestamp
    @Mapping(target = "updatedAt",              ignore = true)  // set by @UpdateTimestamp
    @Mapping(target = "deletedAt",              ignore = true)
    @Mapping(target = "deletedBy",              ignore = true)
    @Mapping(target = "version",                ignore = true)  // optimistic-lock version, DB owns this
    @Mapping(target = "ownerUserId",            ignore = true)  // stamped on persist by OwnershipEntityListener
    @Mapping(target = "assignedUserId",         ignore = true)  // resolved by BookingAssigneeResolver
                                                                // (dto carries a publicId, entity a Long id)
    @Mapping(target = "customerId",             ignore = true)  // resolved by CustomerService.resolveOrCreate
                                                                // from the nested `customer` block
    @Mapping(target = "customerPublicId",       ignore = true)  // stamped by the service alongside customerId
    @Mapping(target = "leadId",                 ignore = true)  // dto carries leadPublicId; the service
                                                                // resolves it tenant-scoped to a Long
    @Mapping(target = "tripSnapshot",           ignore = true)  // built by the service (needs the saved
                                                                // Booking for the back-reference)
    Booking toEntity(CreateBookingRequestDTO dto);

    // ── UpdateBookingRequestDTO → Booking (partial patch) ─────────────────────
    //
    // Only fields the client is allowed to change are mapped.
    // Status changes are intentionally excluded — they go through
    // BookingService.transitionStatus() which validates the state machine.
    // Financial recalculation happens in the service after this call.

    @Mapping(target = "id",                     ignore = true)
    @Mapping(target = "publicId",               ignore = true)
    @Mapping(target = "tenantId",               ignore = true)  // never changeable
    @Mapping(target = "bookingCode",            ignore = true)  // never changeable
    @Mapping(target = "customerId",             ignore = true)  // never changeable after creation
    @Mapping(target = "customerPublicId",       ignore = true)  // never changeable after creation
    @Mapping(target = "tripSnapshot",           ignore = true)  // updated explicitly as an owned aggregate
    @Mapping(target = "customerNameSnapshot",   ignore = true)
    @Mapping(target = "destinationId",          ignore = true)  // resolved by service if destination changed
    @Mapping(target = "destinationSnapshot",    ignore = true)
    @Mapping(target = "leadId",                 ignore = true)  // never changeable
    @Mapping(target = "sourceLeadPublicId",     ignore = true)  // never changeable after creation
    @Mapping(target = "sourceQuotationPublicId", ignore = true) // never changeable after creation
    @Mapping(target = "cancellationPolicyPublicId", ignore = true) // pinned once at creation, immutable
    @Mapping(target = "cancellationPolicyVersion",  ignore = true) // pinned once at creation, immutable
    @Mapping(target = "gst",                    ignore = true)  // recalculated by service
    @Mapping(target = "tcs",                    ignore = true)  // recalculated by service
    @Mapping(target = "totalPayable",           ignore = true)  // recalculated by service
    @Mapping(target = "paidAmount",             ignore = true)  // updated via payment endpoint only
    @Mapping(target = "refundedAmount",         ignore = true)  // updated via refund flow only
    @Mapping(target = "totalInternalCosts",     ignore = true)  // summed from the expense ledger
    @Mapping(target = "totalVendorCosts",       ignore = true)  // summed from the expense ledger
    @Mapping(target = "netProfit",              ignore = true)  // recalculated by BookingProfitService
    @Mapping(target = "vendorPublicId",         ignore = true)  // resolved + validated by service
    @Mapping(target = "vendorName",             ignore = true)  // snapshotted by service
    @Mapping(target = "status",                 ignore = true)  // via transitionStatus() only
    @Mapping(target = "paymentStatus",          ignore = true)  // derived from paidAmount
    @Mapping(target = "services",               ignore = true)  // handled separately
    @Mapping(target = "createdBy",              ignore = true)
    @Mapping(target = "updatedBy",              ignore = true)
    @Mapping(target = "createdAt",              ignore = true)
    @Mapping(target = "updatedAt",              ignore = true)
    @Mapping(target = "deletedAt",              ignore = true)
    @Mapping(target = "deletedBy",              ignore = true)
    @Mapping(target = "version",                ignore = true)  // optimistic-lock version, DB owns this
    @Mapping(target = "ownerUserId",            ignore = true)  // owner never changes after creation
    @Mapping(target = "assignedUserId",         ignore = true)  // tenant-safe resolution in service
    void updateEntity(UpdateBookingRequestDTO dto, @MappingTarget Booking booking);

    // ── Booking → BookingResponseDTO (full detail) ────────────────────────────
    //
    // Maps ALL fields including sensitive ones (netProfit, vendorCost).
    // The service layer is responsible for calling the right method:
    //   - toResponse()        for ADMIN / MANAGER roles
    //   - toSummary()         for AGENT role
    // Never call toResponse() without a permission check in the service.
    //
    // `assignees` is a @Context, not a source: the entity holds only the assignee's internal Long
    // id, and turning that into a publicId + name needs a user read this mapper must not do. The
    // service builds the view ONCE per response (one query for a whole page) and passes it in, so
    // there is no per-row lookup here — see BookingAssigneeViewFactory.

    @Mapping(target = "pendingAmount",    expression = "java(booking.getPendingAmount())")
    @Mapping(target = "assignedUserId",   expression = "java(assignees.publicIdOf(booking.getAssignedUserId()))")
    @Mapping(target = "assignedUserName", expression = "java(assignees.nameOf(booking.getAssignedUserId()))")
    // The API exposes UUIDs, the entity holds internal Longs alongside their denormalised publicIds.
    // Both are explicit because the field NAMES collide (entity customerId:Long vs dto customerId:UUID)
    // and MapStruct would otherwise try to convert a Long into a UUID and fail the build.
    @Mapping(target = "customerId",    source = "customerPublicId")
    @Mapping(target = "leadId",        source = "sourceLeadPublicId")
    // Never populated by any code path — the column exists but nothing writes it. Left on the DTO
    // for wire compatibility; ignored here so MapStruct does not attempt Long -> UUID.
    @Mapping(target = "destinationId", ignore = true)
    // Deliberately NOT mapped: the association is LAZY, and mapping it here would fire per row on
    // every list/page response — plus a second and third query each for its itinerary legs and
    // assistance types. The service attaches it on the single-booking reads only, where the detail
    // screen actually needs it. See BookingServiceImpl.toResponse(Booking).
    @Mapping(target = "tripSnapshot",  ignore = true)
    BookingResponseDTO toResponse(Booking booking, @Context BookingAssigneeView assignees);

    // ── Booking → BookingSummaryDTO (restricted view) ─────────────────────────
    //
    // Safe for AGENT role — no financial internals exposed.
    // vendorCost and netProfit are NOT in this DTO by design.

    @Mapping(target = "pendingAmount", expression = "java(booking.getPendingAmount())")
    BookingSummaryDTO toSummary(Booking booking);
}
