package com.crm.travelcrm.booking.mapper;

import com.crm.travelcrm.booking.dto.request.CreateBookingRequestDTO;
import com.crm.travelcrm.booking.dto.request.UpdateBookingRequestDTO;
import com.crm.travelcrm.booking.dto.response.BookingResponseDTO;
import com.crm.travelcrm.booking.dto.response.BookingSummaryDTO;
import com.crm.travelcrm.booking.entity.Booking;
import org.mapstruct.*;


@Mapper(
        componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE,
        // If a destination field has no source, fail at compile time — not silently
        unmappedTargetPolicy = ReportingPolicy.ERROR
)
public interface BookingMapper {

    // ── CreateBookingRequestDTO → Booking ─────────────────────────────────────
    //
    // Rule: mapper only maps what the CLIENT sends.
    // Everything the SERVER owns is ignored here and set by the service.
    // This makes it impossible to accidentally trust client-supplied values
    // for server-owned fields like tenantId, bookingCode, netProfit.

    @Mapping(target = "id",                     ignore = true)
    @Mapping(target = "publicId",               ignore = true)
    @Mapping(target = "tenantId",               ignore = true)  // set by service from JWT
    @Mapping(target = "bookingCode",            ignore = true)  // generated by service
    @Mapping(target = "customerNameSnapshot",   ignore = true)  // resolved by service
    @Mapping(target = "destinationId",          ignore = true)  // resolved by service
    @Mapping(target = "destinationSnapshot",    ignore = true)  // resolved by service
    @Mapping(target = "gst",                    ignore = true)  // calculated by service
    @Mapping(target = "tcs",                    ignore = true)  // calculated by service
    @Mapping(target = "totalPayable",           ignore = true)  // calculated by service
    @Mapping(target = "netProfit",              ignore = true)  // GENERATED column, DB owns this
    @Mapping(target = "paidAmount",             ignore = true)  // starts at 0
    @Mapping(target = "status",                 ignore = true)  // starts as PENDING
    @Mapping(target = "paymentStatus",          ignore = true)  // starts as UNPAID
    @Mapping(target = "services",               ignore = true)  // mapped separately below
    @Mapping(target = "createdBy",              ignore = true)  // set by @CreatedBy auditing
    @Mapping(target = "updatedBy",              ignore = true)  // set by @LastModifiedBy
    @Mapping(target = "createdAt",              ignore = true)  // set by @CreationTimestamp
    @Mapping(target = "updatedAt",              ignore = true)  // set by @UpdateTimestamp
    @Mapping(target = "deletedAt",              ignore = true)
    @Mapping(target = "deletedBy",              ignore = true)
    @Mapping(target = "active",                 ignore = true)
    Booking toEntity(CreateBookingRequestDTO dto);

    // ── UpdateBookingRequestDTO → Booking (partial patch) ─────────────────────
    //
    // Only fields the client is allowed to change are mapped.
    // Status changes are intentionally excluded — they go through
    // BookingService.transitionStatus() which validates the state machine.
    // Financial recalculation happens in the service after this call.

    @Mapping(target = "id",                     ignore = true)
    @Mapping(target = "publicId",               ignore = true)
    @Mapping(target = "tenantId",               ignore = true)  // never changeable
    @Mapping(target = "bookingCode",            ignore = true)  // never changeable
    @Mapping(target = "customerId",             ignore = true)  // never changeable after creation
    @Mapping(target = "customerNameSnapshot",   ignore = true)
    @Mapping(target = "destinationId",          ignore = true)  // resolved by service if destination changed
    @Mapping(target = "destinationSnapshot",    ignore = true)
    @Mapping(target = "leadId",                 ignore = true)  // never changeable
    @Mapping(target = "gst",                    ignore = true)  // recalculated by service
    @Mapping(target = "tcs",                    ignore = true)  // recalculated by service
    @Mapping(target = "totalPayable",           ignore = true)  // recalculated by service
    @Mapping(target = "paidAmount",             ignore = true)  // updated via payment endpoint only
    @Mapping(target = "netProfit",              ignore = true)  // GENERATED column
    @Mapping(target = "status",                 ignore = true)  // via transitionStatus() only
    @Mapping(target = "paymentStatus",          ignore = true)  // derived from paidAmount
    @Mapping(target = "services",               ignore = true)  // handled separately
    @Mapping(target = "createdBy",              ignore = true)
    @Mapping(target = "updatedBy",              ignore = true)
    @Mapping(target = "createdAt",              ignore = true)
    @Mapping(target = "updatedAt",              ignore = true)
    @Mapping(target = "deletedAt",              ignore = true)
    @Mapping(target = "deletedBy",              ignore = true)
    @Mapping(target = "active",                 ignore = true)
    void updateEntity(UpdateBookingRequestDTO dto, @MappingTarget Booking booking);

    // ── Booking → BookingResponseDTO (full detail) ────────────────────────────
    //
    // Maps ALL fields including sensitive ones (netProfit, vendorCost).
    // The service layer is responsible for calling the right method:
    //   - toResponse()        for ADMIN / MANAGER roles
    //   - toSummary()         for AGENT role
    // Never call toResponse() without a permission check in the service.

    @Mapping(target = "pendingAmount", expression = "java(booking.getPendingAmount())")
    BookingResponseDTO toResponse(Booking booking);

    // ── Booking → BookingSummaryDTO (restricted view) ─────────────────────────
    //
    // Safe for AGENT role — no financial internals exposed.
    // vendorCost and netProfit are NOT in this DTO by design.

    @Mapping(target = "pendingAmount", expression = "java(booking.getPendingAmount())")
    BookingSummaryDTO toSummary(Booking booking);
}