-- ============================================================================
-- V1__create_all_tables.sql
-- Baseline schema for Travel CRM (PostgreSQL).
-- Multi-tenancy: every tenant-scoped table carries tenant_id.
-- city_master: tenant_id nullable — NULL = global, non-null = tenant-owned.
-- super_admins is platform-level — no tenant_id.
-- ============================================================================

-- ============================================================================
-- 1. TENANTS
-- ============================================================================
CREATE TABLE tenants (
                         id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         public_id               UUID         NOT NULL,
                         created_by              VARCHAR(255),
                         updated_by              VARCHAR(255),
                         created_at              TIMESTAMP    NOT NULL,
                         updated_at              TIMESTAMP    NOT NULL,
                         deleted_at              TIMESTAMP,
                         deleted_by              VARCHAR(255),
                         organization_name       VARCHAR(150) NOT NULL,
                         organization_code       VARCHAR(50)  NOT NULL,
                         email                   VARCHAR(150) NOT NULL,
                         phone                   VARCHAR(20),
                         address                 VARCHAR(255),
                         plan                    VARCHAR(20)  NOT NULL DEFAULT 'STARTER',
                         status                  VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
                         subscription_start_date DATE,
                         subscription_end_date   DATE,
                         max_users               INTEGER      NOT NULL DEFAULT 5,
                         CONSTRAINT uq_tenants_public_id         UNIQUE (public_id),
                         CONSTRAINT uq_tenants_organization_code UNIQUE (organization_code),
                         CONSTRAINT uq_tenants_email             UNIQUE (email)
);

CREATE INDEX idx_tenant_email             ON tenants (email);
CREATE INDEX idx_tenant_organization_code ON tenants (organization_code);

-- ============================================================================
-- 2. SUPER_ADMINS
-- ============================================================================
CREATE TABLE super_admins (
                              id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              public_id  UUID         NOT NULL,
                              created_by VARCHAR(255),
                              updated_by VARCHAR(255),
                              created_at TIMESTAMP    NOT NULL,
                              updated_at TIMESTAMP    NOT NULL,
                              deleted_at TIMESTAMP,
                              deleted_by VARCHAR(255),
                              name       VARCHAR(150) NOT NULL,
                              email      VARCHAR(150) NOT NULL,
                              password   VARCHAR(255) NOT NULL,
                              enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
                              CONSTRAINT uq_super_admins_public_id UNIQUE (public_id),
                              CONSTRAINT uq_super_admins_email     UNIQUE (email)
);

-- ============================================================================
-- 3. USERS
-- ============================================================================
CREATE TABLE users (
                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       public_id    UUID         NOT NULL,
                       created_by   VARCHAR(255),
                       updated_by   VARCHAR(255),
                       created_at   TIMESTAMP    NOT NULL,
                       updated_at   TIMESTAMP    NOT NULL,
                       deleted_at   TIMESTAMP,
                       deleted_by   VARCHAR(255),
                       tenant_id    BIGINT,
                       full_name    VARCHAR(150) NOT NULL,
                       email        VARCHAR(150) NOT NULL,
                       password     VARCHAR(255) NOT NULL,
                       role         VARCHAR(30)  NOT NULL,
                       phone_number VARCHAR(20),
                       is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
                       CONSTRAINT uq_users_public_id   UNIQUE (public_id),
                       CONSTRAINT uq_user_email_tenant UNIQUE (email, tenant_id),
                       CONSTRAINT fk_users_tenant      FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE INDEX idx_user_email  ON users (email);
CREATE INDEX idx_user_tenant ON users (tenant_id);
CREATE INDEX idx_user_role   ON users (role);

-- ============================================================================
-- 4. CITY_MASTER
--    tenant_id nullable: NULL = global (all tenants), non-null = tenant-owned.
-- ============================================================================
CREATE TABLE city_master (
                             city_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             country_name VARCHAR(100) NOT NULL,
                             city_name    VARCHAR(100) NOT NULL,
                             airport_code VARCHAR(10),
                             status       VARCHAR(20),
                             tenant_id    BIGINT       DEFAULT NULL,
                             created_at   TIMESTAMP    NOT NULL,
                             CONSTRAINT fk_city_master_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE INDEX idx_city_master_country ON city_master (country_name);
CREATE INDEX idx_city_master_city    ON city_master (city_name);
CREATE INDEX idx_city_master_tenant  ON city_master (tenant_id);

-- ============================================================================
-- 5. DESTINATION_MASTER
-- ============================================================================
CREATE TABLE destination_master (
                                    destination_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    country               VARCHAR(100) NOT NULL,
                                    name                  VARCHAR(200) NOT NULL,
                                    type                  VARCHAR(50),
                                    image_path            VARCHAR(500),
                                    inclusions            TEXT,
                                    exclusions            TEXT,
                                    payment_policies      TEXT,
                                    cancellation_policies TEXT,
                                    booking_terms         TEXT,
                                    status                VARCHAR(20),
                                    created_at            TIMESTAMP    NOT NULL
);

CREATE INDEX idx_destination_master_country ON destination_master (country);
CREATE INDEX idx_destination_master_name    ON destination_master (name);

-- ============================================================================
-- 6. LEADS
-- ============================================================================
CREATE TABLE leads (
                       id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       public_id      UUID         NOT NULL,
                       created_by     VARCHAR(255),
                       updated_by     VARCHAR(255),
                       created_at     TIMESTAMP    NOT NULL,
                       updated_at     TIMESTAMP    NOT NULL,
                       deleted_at     TIMESTAMP,
                       deleted_by     VARCHAR(255),
                       tenant_id      BIGINT       NOT NULL,
                       customer_name  VARCHAR(150) NOT NULL,
                       phone          VARCHAR(20)  NOT NULL,
                       email          VARCHAR(150) NOT NULL,
                       lead_source    VARCHAR(50)  NOT NULL,
                       lead_type      VARCHAR(50)  NOT NULL,
                       lead_stage     VARCHAR(50)  NOT NULL,
                       assign_to      VARCHAR(100),
                       birth_date     DATE,
                       travel_date    DATE,
                       depart_country VARCHAR(100),
                       depart_city    VARCHAR(100),
                       rooms          INTEGER,
                       adults         INTEGER,
                       children       INTEGER,
                       infants        INTEGER,
                       extra_beds     INTEGER,
                       notes          TEXT,
                       CONSTRAINT uq_leads_public_id   UNIQUE (public_id),
                       CONSTRAINT uk_lead_tenant_email UNIQUE (tenant_id, email),
                       CONSTRAINT uk_lead_tenant_phone UNIQUE (tenant_id, phone),
                       CONSTRAINT fk_leads_tenant      FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE INDEX idx_lead_email  ON leads (email);
CREATE INDEX idx_lead_phone  ON leads (phone);
CREATE INDEX idx_lead_tenant ON leads (tenant_id);
CREATE INDEX idx_lead_stage  ON leads (tenant_id, lead_stage);

-- ============================================================================
-- 7. LEAD_SERVICES
-- ============================================================================
CREATE TABLE lead_services (
                               lead_id BIGINT NOT NULL,
                               service VARCHAR(255),
                               CONSTRAINT fk_lead_services_lead FOREIGN KEY (lead_id) REFERENCES leads (id)
);

CREATE INDEX idx_lead_services_lead ON lead_services (lead_id);

-- ============================================================================
-- 8. LEAD_ITINERARY
-- ============================================================================
CREATE TABLE lead_itinerary (
                                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                public_id   UUID         NOT NULL,
                                created_by  VARCHAR(255),
                                updated_by  VARCHAR(255),
                                created_at  TIMESTAMP    NOT NULL,
                                updated_at  TIMESTAMP    NOT NULL,
                                deleted_at  TIMESTAMP,
                                deleted_by  VARCHAR(255),
                                lead_id     BIGINT       NOT NULL,
                                destination VARCHAR(100) NOT NULL,
                                city        VARCHAR(100) NOT NULL,
                                nights      INTEGER      NOT NULL,
                                day_number  INTEGER,
                                CONSTRAINT uq_lead_itinerary_public_id UNIQUE (public_id),
                                CONSTRAINT fk_lead_itinerary_lead      FOREIGN KEY (lead_id) REFERENCES leads (id)
);

CREATE INDEX idx_itinerary_lead ON lead_itinerary (lead_id);

-- ============================================================================
-- 9. BOOKINGS
-- ============================================================================
CREATE TABLE bookings (
                          id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          public_id              UUID           NOT NULL,
                          created_by             VARCHAR(255),
                          updated_by             VARCHAR(255),
                          created_at             TIMESTAMP      NOT NULL,
                          updated_at             TIMESTAMP      NOT NULL,
                          deleted_at             TIMESTAMP,
                          deleted_by             VARCHAR(255),
                          tenant_id              BIGINT         NOT NULL,
                          booking_code           VARCHAR(20)    NOT NULL,
                          customer_id            BIGINT         NOT NULL,
                          customer_name_snapshot VARCHAR(255)   NOT NULL,
                          destination_id         BIGINT,
                          destination_snapshot   VARCHAR(255)   NOT NULL,
                          lead_id                BIGINT,
                          customer_amount        NUMERIC(12, 2) NOT NULL DEFAULT 0,
                          vendor_cost            NUMERIC(12, 2) NOT NULL DEFAULT 0,
                          gst                    NUMERIC(12, 2) NOT NULL DEFAULT 0,
                          tcs                    NUMERIC(12, 2) NOT NULL DEFAULT 0,
                          total_payable          NUMERIC(12, 2) NOT NULL DEFAULT 0,
                          paid_amount            NUMERIC(12, 2) NOT NULL DEFAULT 0,
                          net_profit             NUMERIC(12, 2) NOT NULL DEFAULT 0,
                          status                 VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
                          payment_status         VARCHAR(20)    NOT NULL DEFAULT 'UNPAID',
                          booking_date           DATE           NOT NULL,
                          travel_date            DATE           NOT NULL,
                          active                 BOOLEAN        NOT NULL DEFAULT TRUE,
                          CONSTRAINT uq_bookings_public_id   UNIQUE (public_id),
                          CONSTRAINT fk_bookings_tenant      FOREIGN KEY (tenant_id)      REFERENCES tenants (id),
                          CONSTRAINT fk_bookings_lead        FOREIGN KEY (lead_id)        REFERENCES leads (id),
                          CONSTRAINT fk_bookings_destination FOREIGN KEY (destination_id) REFERENCES destination_master (destination_id)
);

CREATE INDEX idx_booking_tenant      ON bookings (tenant_id);
CREATE INDEX idx_booking_code        ON bookings (tenant_id, booking_code);
CREATE INDEX idx_booking_customer    ON bookings (customer_id);
CREATE INDEX idx_booking_status      ON bookings (tenant_id, status);
CREATE INDEX idx_booking_travel_date ON bookings (tenant_id, travel_date);
CREATE INDEX idx_booking_deleted     ON bookings (tenant_id, deleted_at);
CREATE INDEX idx_booking_lead        ON bookings (lead_id);
CREATE INDEX idx_booking_destination ON bookings (destination_id);

-- ============================================================================
-- 10. BOOKING_SERVICES
-- ============================================================================
CREATE TABLE booking_services (
                                  booking_id   BIGINT NOT NULL,
                                  service_name VARCHAR(100),
                                  CONSTRAINT fk_booking_services_booking FOREIGN KEY (booking_id) REFERENCES bookings (id)
);

CREATE INDEX idx_booking_services_booking ON booking_services (booking_id);

-- ============================================================================
-- 11. NOTIFICATIONS
-- ============================================================================
CREATE TABLE notifications (
                               id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               public_id           UUID         NOT NULL,
                               created_by          VARCHAR(255),
                               updated_by          VARCHAR(255),
                               created_at          TIMESTAMP    NOT NULL,
                               updated_at          TIMESTAMP    NOT NULL,
                               deleted_at          TIMESTAMP,
                               deleted_by          VARCHAR(255),
                               tenant_id           BIGINT       NOT NULL,
                               recipient_user_id   BIGINT       NOT NULL,
                               type                VARCHAR(100) NOT NULL,
                               title               VARCHAR(255) NOT NULL,
                               message             TEXT,
                               status              VARCHAR(20)  NOT NULL DEFAULT 'UNREAD',
                               reference_type      VARCHAR(50),
                               reference_public_id UUID,
                               read_at             TIMESTAMPTZ,
                               CONSTRAINT uq_notifications_public_id UNIQUE (public_id),
                               CONSTRAINT fk_notifications_tenant    FOREIGN KEY (tenant_id)         REFERENCES tenants (id),
                               CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_user_id) REFERENCES users (id)
);

CREATE INDEX idx_notification_tenant    ON notifications (tenant_id);
CREATE INDEX idx_notification_recipient ON notifications (tenant_id, recipient_user_id, status);

-- ============================================================================
-- 12. REMINDERS
-- ============================================================================
CREATE TABLE reminders (
                           id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           public_id           UUID         NOT NULL,
                           created_by          VARCHAR(255),
                           updated_by          VARCHAR(255),
                           created_at          TIMESTAMP    NOT NULL,
                           updated_at          TIMESTAMP    NOT NULL,
                           deleted_at          TIMESTAMP,
                           deleted_by          VARCHAR(255),
                           tenant_id           BIGINT       NOT NULL,
                           owner_user_id       BIGINT       NOT NULL,
                           title               VARCHAR(255) NOT NULL,
                           notes               TEXT,
                           remind_at           TIMESTAMPTZ  NOT NULL,
                           status              VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
                           snoozed_until       TIMESTAMPTZ,
                           reference_type      VARCHAR(50),
                           reference_public_id UUID,
                           CONSTRAINT uq_reminders_public_id UNIQUE (public_id),
                           CONSTRAINT fk_reminders_tenant    FOREIGN KEY (tenant_id)     REFERENCES tenants (id),
                           CONSTRAINT fk_reminders_owner     FOREIGN KEY (owner_user_id) REFERENCES users (id)
);

CREATE INDEX idx_reminder_tenant ON reminders (tenant_id);
CREATE INDEX idx_reminder_owner  ON reminders (tenant_id, owner_user_id);
CREATE INDEX idx_reminder_due    ON reminders (status, remind_at);

-- ============================================================================
-- 13. ENVERS AUDIT TABLES
-- ============================================================================
CREATE SEQUENCE revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE revinfo (
                         rev      INTEGER NOT NULL PRIMARY KEY,
                         revtstmp BIGINT
);

CREATE TABLE bookings_aud (
                              id                     BIGINT   NOT NULL,
                              rev                    INTEGER  NOT NULL,
                              revtype                SMALLINT,
                              public_id              UUID,
                              created_by             VARCHAR(255),
                              updated_by             VARCHAR(255),
                              created_at             TIMESTAMP,
                              updated_at             TIMESTAMP,
                              deleted_at             TIMESTAMP,
                              deleted_by             VARCHAR(255),
                              tenant_id              BIGINT,
                              booking_code           VARCHAR(20),
                              customer_id            BIGINT,
                              customer_name_snapshot VARCHAR(255),
                              destination_id         BIGINT,
                              destination_snapshot   VARCHAR(255),
                              lead_id                BIGINT,
                              customer_amount        NUMERIC(12, 2),
                              vendor_cost            NUMERIC(12, 2),
                              gst                    NUMERIC(12, 2),
                              tcs                    NUMERIC(12, 2),
                              total_payable          NUMERIC(12, 2),
                              paid_amount            NUMERIC(12, 2),
                              net_profit             NUMERIC(12, 2),
                              status                 VARCHAR(20),
                              payment_status         VARCHAR(20),
                              booking_date           DATE,
                              travel_date            DATE,
                              active                 BOOLEAN,
                              CONSTRAINT pk_bookings_aud     PRIMARY KEY (rev, id),
                              CONSTRAINT fk_bookings_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE INDEX idx_bookings_aud_rev ON bookings_aud (rev);