-- Human-readable lead reference: leads.lead_code (LD-YY-NNNN) + its per-tenant counter table.
--
-- WHY: the lead UI had nothing to display but publicId, a raw UUID — not something anyone can read
-- out on a phone call. Bookings solved this long ago (bookings.booking_code, BKG-YY-NNNN); leads
-- never got the same treatment. publicId stays the API/routing key and is unchanged; this is purely
-- an additive DISPLAY identity.
--
-- SELF-SUFFICIENT ON PURPOSE. Under JPA_DDL_AUTO=validate Hibernate creates nothing, so this file
-- must do every piece: column, counter table, backfill, counter seed, indexes. It is also fully
-- idempotent, because it can legitimately meet a database that already has all of it — the pilot
-- may have taken this change on the old ddl-auto=update + db/indexes.sql path before the Flyway
-- cutover. Every statement below is a no-op in that case.

-- ── 1. Schema ───────────────────────────────────────────────────────────────
-- varchar(20) matches @Column(name = "lead_code", length = 20) on Lead; a mismatch here is exactly
-- what JPA_DDL_AUTO=validate refuses to boot on.
ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_code varchar(20);

-- The counter. Column order/types copied from the generated booking_sequences DDL in V1 so the two
-- stay identical — LeadSequence is deliberately a plain @Entity (no publicId/audit/soft-delete and
-- NO Hibernate tenantFilter), for the same reason BookingSequence is: the generator reads it under
-- a pessimistic lock keyed explicitly by tenant_id, and the filter would interfere with that read.
CREATE TABLE IF NOT EXISTS lead_sequences (
    id bigint generated by default as identity,
    last_value bigint not null,
    tenant_id bigint not null,
    primary key (id),
    constraint uk_lead_sequence_tenant unique (tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_lead_code ON leads (tenant_id, lead_code);

-- ── 2. Backfill existing rows ───────────────────────────────────────────────
-- Numbered per tenant by id (chronological); the year comes from the row's own created_at so a 2025
-- lead does not claim a 2026 prefix. Soft-deleted rows are included deliberately: they keep their
-- number, and skipping them would let the counter seed below hand out a code that already exists.
-- Touches only lead_code IS NULL, so re-running is a no-op.
-- created_at is NOT NULL in V1, so it is read directly: a COALESCE onto now() would drag a
-- timestamptz into a timestamp expression for no benefit.
UPDATE leads l
   SET lead_code = 'LD-' || to_char(l.created_at, 'YY') || '-'
                         || lpad(n.rn::text, 4, '0')
  FROM (SELECT id,
               row_number() OVER (PARTITION BY tenant_id ORDER BY id) AS rn
          FROM leads
         WHERE lead_code IS NULL) n
 WHERE l.id = n.id;

-- ── 3. Seed the counter ─────────────────────────────────────────────────────
-- So the generator resumes ABOVE the back-filled codes instead of re-issuing LD-YY-0001 and dying
-- on uq_leads_code_tenant. count(*) rather than the max back-filled rn, so a database whose rows
-- were already coded another way (the dev seeder writes LD1000x literals) still starts above its
-- own row count. ON CONFLICT DO NOTHING: an existing counter row is the truth, never this.
--
-- Belt-and-braces, not the only guard: LeadCodeGenerator.createInitial() seeds a missing counter
-- from the same row count, so a tenant whose counter never got seeded here still cannot collide.
INSERT INTO lead_sequences (tenant_id, last_value)
SELECT tenant_id, count(*) FROM leads GROUP BY tenant_id
ON CONFLICT (tenant_id) DO NOTHING;

-- ── 4. Uniqueness ───────────────────────────────────────────────────────────
-- Partial (not absolute) so a row the backfill could not reach does not block index creation.
-- Soft-deleted rows ARE covered on purpose: a code is quoted to a customer and must never be
-- reissued, even after the lead is trashed. This differs from uq_customers_code_tenant /
-- uq_vendors_code_tenant, which exclude deleted rows so a code can be reused — the opposite choice,
-- made here because a lead code is an outward-facing reference, not an internal slot.
CREATE UNIQUE INDEX IF NOT EXISTS uq_leads_code_tenant
        ON leads (lead_code, tenant_id) WHERE lead_code IS NOT NULL;

-- ── NOT DONE HERE: the NOT NULL hardening ───────────────────────────────────
-- Every write path is covered (LeadServiceImpl.createLead is the single creation point for manual,
-- inbound-ingest and sub-agent leads; DevDataSeeder sets a literal), so it should be safe — but a
-- NOT NULL that meets one stray NULL fails the migration and blocks the deploy. Confirm on the real
-- database first:
--
--   SELECT count(*) FROM leads WHERE lead_code IS NULL;
--
-- and only then add it as its own migration:
--
--   ALTER TABLE leads ALTER COLUMN lead_code SET NOT NULL;


-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- PART 2 — tenant staff log in with a USERNAME, not an email
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- Carried in V2 rather than a new V3 because V2 has never been applied or stamped anywhere: it is
-- untracked in git, spring.flyway.enabled defaults to false, and FLYWAY_ENABLED is still commented
-- out in deploy/travelcrm.env.example. No flyway_schema_history row records its checksum, so editing
-- it in place cannot fail a later validate. Once this file HAS been applied somewhere shared, that
-- stops being true and the next change must be its own V — see the warning at the top of V1.
--
-- WHY: users.email was unique platform-wide (uq_users_email_active), which forced every staff member
-- of an agency to hold a personal address — an agency with one shared info@ mailbox could provision
-- exactly one account. Email becomes a contact/display field, free to repeat, and the login identity
-- moves to a new users.username. Something must stay unique or login is ambiguous, and it must be
-- unique GLOBALLY, not per tenant: the login form takes no organization, so the tenant is a result
-- of the lookup, never an input to it.
--
-- SuperAdmin is untouched. That realm lives in super_admins, authenticates through a separate
-- endpoint/service, and is still keyed by email.

-- ── 5. Schema ───────────────────────────────────────────────────────────────
-- varchar(80) matches @Column(name = "username", length = 80) on User. The entity leaves the field
-- JPA-nullable on purpose (see the comment there) so the ddl-auto=update path can add the column to
-- a populated table; NOT NULL is applied here, after the backfill, on the Flyway path.
ALTER TABLE users ADD COLUMN IF NOT EXISTS username varchar(80);

-- ── 6. Backfill existing rows ───────────────────────────────────────────────
-- Derived from the email local-part, stripped to the username charset ([a-z0-9._-]) and capped at 60
-- so the "_<id>" disambiguator below still fits inside varchar(80). Mirrors
-- UsernamePolicy.stemFromEmail so a row repaired here and a row created by the application have the
-- same shape.
--
-- Collision-safe rather than unconditionally suffixed: appending "_<id>" to EVERY row is trivially
-- unique but hands every existing user an ugly login (prasad_17) for a collision that mostly does
-- not exist. So the first claimant of a stem keeps it clean and only genuine duplicates — exactly
-- the shared-mailbox rows this change enables — get "_<id>".
--   * rn = 1        → first row (by id) for that stem
--   * NOT taken     → no row already holds that username (guards a partial re-run)
-- row_number() partitions over ALL rows including soft-deleted ones, even though the unique index
-- only covers live rows: a deleted row keeping a distinct username costs nothing and removes any
-- chance of the backfill and the index disagreeing.
--
-- Touches only NULL/empty username, so re-running is a no-op.
WITH candidate AS (
    SELECT id,
           COALESCE(
               NULLIF(left(regexp_replace(lower(split_part(email, '@', 1)), '[^a-z0-9._-]', '', 'g'),
                           60), ''),
               'user'
           ) AS stem
      FROM users
     WHERE username IS NULL OR username = ''
),
ranked AS (
    SELECT c.id,
           c.stem,
           row_number() OVER (PARTITION BY c.stem ORDER BY c.id) AS rn,
           EXISTS (SELECT 1 FROM users x WHERE x.username = c.stem) AS taken
      FROM candidate c
)
UPDATE users u
   SET username = CASE WHEN r.rn = 1 AND NOT r.taken THEN r.stem
                       ELSE r.stem || '_' || u.id END
  FROM ranked r
 WHERE u.id = r.id;

-- Safe now: the backfill above leaves no NULL behind (every users row has a NOT NULL email to derive
-- from, and the COALESCE covers an address whose local-part strips to nothing).
ALTER TABLE users ALTER COLUMN username SET NOT NULL;

-- ── 7. Swap the uniqueness ──────────────────────────────────────────────────
-- Retire the email constraint FIRST. Leaving it would silently defeat the whole change — the second
-- user given the shared office address would still be rejected. It is an index (created by
-- CREATE UNIQUE INDEX in V1/db/indexes.sql), not a table constraint, so DROP INDEX is the right verb;
-- the DROP CONSTRAINT covers the older uq_user_email_tenant on databases predating that switch.
DROP INDEX IF EXISTS uq_users_email_active;
ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_user_email_tenant;

-- Partial on deleted_at IS NULL, matching how uq_users_email_active worked and for the same reason:
-- an absolute UNIQUE(username) would let a soft-deleted account squat on a name forever. Every
-- username read in the application filters deleted_at, so this index serves the login lookup, the
-- uniqueness guard and the availability check — which is why no second plain index on username is
-- created here.
--
-- ⚠ If this fails, it leaves NO unique constraint on username and login becomes ambiguous. Flyway
-- aborts the migration on failure (unlike db/indexes.sql, which runs with continue-on-error=true),
-- so on the Flyway path a failure blocks the deploy rather than passing silently. Offenders:
--   SELECT username, count(*) FROM users WHERE deleted_at IS NULL
--    GROUP BY username HAVING count(*) > 1;
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username_active
        ON users (username)
        WHERE deleted_at IS NULL;

-- Email keeps a plain, NON-unique index. Already created by V1 from the entity's @Index; repeated
-- here as an idempotent safety net so the invariant holds on a database that reached this point by
-- the ddl-auto route instead.
CREATE INDEX IF NOT EXISTS idx_user_email ON users (email);

-- ── 8. The audit trail records the username too ─────────────────────────────
-- activity_logs stored user_name + user_email and the Activity Report SYNTHESIZED a username by
-- splitting the email local-part (ActivityReportMapper.deriveUsername). That was already a guess;
-- with a shared office mailbox it becomes actively wrong — every colleague would be labelled
-- "@info", an audit trail that cannot tell three people apart. Store the real one.
--
-- Nullable, with no NOT NULL follow-up: rows written before this column existed legitimately have
-- none, and the mapper still falls back to the old derivation for exactly those.
ALTER TABLE activity_logs ADD COLUMN IF NOT EXISTS username varchar(80);

-- Backfill from the acting user where it is still resolvable. user_id is a logical reference, not a
-- FK, so rows whose user has since been hard-deleted simply keep a NULL username and fall back.
-- Touches only NULL, so re-running is a no-op.
UPDATE activity_logs a
   SET username = u.username
  FROM users u
 WHERE a.user_id = u.id
   AND a.username IS NULL;


-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- PART 3 — booking_expenses: the per-booking expense ledger
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- Carried in V2 for the same reason PART 2 was, and the reason still holds: V2 has been applied
-- LOCALLY ONLY and has never been run or stamped on the deployment database. It remains untracked
-- in git, spring.flyway.enabled defaults to false, and no flyway_schema_history row records its
-- checksum — so editing it in place cannot fail a later validate. A local database that already
-- has PARTS 1-2 simply re-runs them as no-ops (every statement in this file is idempotent) and
-- picks up PART 3. Once this file HAS been applied somewhere shared, that stops being true and the
-- next change must be its own V.
--
-- WHY: bookings recorded what the CUSTOMER pays (customer_amount / paid_amount, itemised in
-- booking_payments) and one lump vendor_cost typed on the booking form, but nothing recorded the
-- individual costs the agency actually incurred, who they were owed to, or how much of each had
-- been paid out. Agencies run most vendor purchases on credit ("udhar"), so the missing figure is
-- not the cost — it is the BALANCE still payable per line, with a due date.
--
-- Deliberately NOT folded into an existing table:
--   * booking_service_items is the OPERATIONAL breakdown (what the traveller gets, vendor
--     assignment, voucher). Its vendor_cost is a planning figure, not a settlement record — it has
--     no paid amount, no due date and no payment state.
--   * booking_payments is money IN from the customer. Adding an outbound direction there would
--     entangle two ledgers whose only shared column is the amount.
--   * vendor_bills (accounting/tds) is the formal payable with TDS and GST against a vendor
--     master. This is the fast cash book, where the payee is often a driver or a local guide who
--     was never onboarded as a vendor — hence vendor_name is free text, not a FK.
--
-- The parent booking's own figures are untouched: no trigger, no backfill into bookings.vendor_cost
-- or bookings.net_profit. Those stay what the user typed on the booking, and the rollup is served
-- by GET /api/bookings/{id}/expenses/summary. See BookingExpense's javadoc for why.

-- ── 9. Schema ───────────────────────────────────────────────────────────────
-- Column order and typing follow exactly what Hibernate would generate for a BaseTenantEntity:
-- id first, then the BaseEntity block alphabetically, then tenant_id, then this entity's own
-- columns alphabetically (NOT Java declaration order), then primary key. Compare the
-- booking_payments line in V1__baseline_schema.sql — the first ten tokens are byte-identical.
-- Getting this wrong is what JPA_DDL_AUTO=validate refuses to boot on.
--
-- payment_status carries the inline CHECK Hibernate emits for @Enumerated(EnumType.STRING); the
-- values must stay in step with the ExpensePaymentStatus enum. Note that ddl-auto never ALTERS an
-- existing CHECK, so adding a constant later needs an explicit DROP/ADD refresh in a new V.
--
-- There is no outstanding_amount column on purpose: the balance is derived (amount - paid_amount)
-- by BookingExpense.getOutstandingAmount(), so it cannot drift from the two columns it comes from.
-- The client posts its own browser-computed outstandingAmount; the API ignores it.
CREATE TABLE IF NOT EXISTS booking_expenses (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    created_by varchar(255),
    deleted_at timestamp(6),
    deleted_by varchar(255),
    public_id uuid not null unique,
    updated_at timestamp(6) not null,
    updated_by varchar(255),
    tenant_id bigint not null,
    amount numeric(12,2) not null,
    booking_id bigint not null,
    category varchar(60),
    description varchar(300) not null,
    due_date date,
    expense_date date not null,
    notes TEXT,
    paid_amount numeric(12,2) not null,
    payment_mode varchar(40),
    payment_status varchar(10) not null check (payment_status in ('CREDIT','PARTIAL','PAID')),
    reference_number varchar(120),
    vendor_name varchar(200),
    primary key (id)
);

-- ── 10. Indexes ─────────────────────────────────────────────────────────────
-- Mirrors the @Index block on BookingExpense's @Table, which in turn mirrors what both sibling
-- child tables carry (idx_bkpay_* / idx_bksvc_*): the tenant column, the list query's
-- (tenant_id, booking_id) pair, and the soft-delete pair every finder filters on. These belong
-- here rather than in db/indexes.sql — that file is only for what JPA annotations CANNOT express
-- (partial-unique indexes, enum CHECK refreshes), and it runs with continue-on-error=true, so a
-- failure there is silent.
CREATE INDEX IF NOT EXISTS idx_bkexp_tenant  on booking_expenses (tenant_id);
CREATE INDEX IF NOT EXISTS idx_bkexp_booking on booking_expenses (tenant_id, booking_id);
CREATE INDEX IF NOT EXISTS idx_bkexp_deleted on booking_expenses (tenant_id, deleted_at);

-- ── NOT DONE HERE: a FK to bookings(id) ─────────────────────────────────────
-- booking_id is a logical FK with no DB constraint, matching booking_payments.booking_id and
-- booking_service_items.booking_id exactly. Booking holds no @OneToMany to its children, so a real
-- constraint would change the behaviour of the Trash hard-purge (TrashServiceImpl em.remove's a
-- BOOKING directly, which would then fail on the surviving child rows instead of orphaning them).
-- That is a decision for the whole booking aggregate, not for one new child table.


-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- PART 4 — Booking Financial Engine: profit, internal costs, cancellation P&L
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- Carried in V2 for the same reason PARTS 2-3 were, and the reason STILL holds: V2 has been applied
-- LOCALLY ONLY and has never been run or stamped on the deployment database. No flyway_schema_history
-- row records its checksum, so editing it in place cannot fail a later validate. A local database
-- that already has PARTS 1-3 simply re-runs them as no-ops — every statement in this file is
-- idempotent — and picks up PART 4. Once this file HAS been applied somewhere shared, that stops
-- being true and the next change must be its own V.
--
-- !! HOW THIS GETS APPLIED !!
-- Flyway is DISABLED on every profile and currently CANNOT be enabled: FLYWAY_ENABLED=true fails to
-- boot on a circular depends-on between the `flyway` and `entityManagerFactory` beans
-- (application.properties:71-81; the @EnableJpaAuditing split was already tried and does not fix it,
-- JpaConfig.java:14-17). Meanwhile ddl-auto=validate, so Hibernate creates NOTHING and the app will
-- REFUSE TO BOOT with a schema-validation error until these columns exist. Run it by hand, on every
-- environment, BEFORE deploying the matching code:
--
--     psql -U <user> -d <db> -f src/main/resources/db/migration/V2__lead_code.sql
--
-- WHY: net_profit was customer_amount − vendor_cost and nothing else. The agency's OWN costs on a
-- booking — staff commission, marketing, payment-gateway fees, documentation/courier — had nowhere
-- to go, so reported margin was systematically overstated by exactly those amounts. The expense
-- ledger from PART 3 already held some of them (its category list ships "Commission" and "Office
-- Expense" alongside "Hotel" and "Flight"), but it could not feed profit: summing it wholesale would
-- subtract supplier cost TWICE, once as the typed vendor_cost and again as an expense row, and a
-- profitable booking would report a loss. PART 4 adds the discriminator that makes the sum safe.
--
-- ZERO-REGRESSION GUARANTEE. cost_type defaults to 'VENDOR' and total_internal_costs to 0, so the
-- instant this runs:
--   * every pre-existing expense row is classified VENDOR ⇒ excluded from profit,
--   * every booking's total_internal_costs is 0.00,
--   * net_profit therefore still equals customer_amount − vendor_cost, unchanged to the paisa.
-- Profit only moves when a user explicitly reclassifies a line as INTERNAL.

-- ── 1. booking_expenses.cost_type ───────────────────────────────────────────
-- VENDOR = supplier cost, already represented by the typed bookings.vendor_cost, so EXCLUDED from
-- profit. INTERNAL = the agency's own overhead, so INCLUDED. This column is the only thing standing
-- between the profit formula and a double-count.
--
-- NOT NULL DEFAULT 'VENDOR' backfills every existing row in the same statement.
ALTER TABLE booking_expenses
    ADD COLUMN IF NOT EXISTS cost_type varchar(10) NOT NULL DEFAULT 'VENDOR';

-- @Enumerated(STRING) columns in this schema carry an inline CHECK listing the allowed values, and
-- ddl-auto never ALTERs an existing CHECK. Adding a third cost type later therefore means editing
-- this constraint by hand, or inserts fail at RUNTIME rather than at boot.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'booking_expenses_cost_type_check'
    ) THEN
        ALTER TABLE booking_expenses
            ADD CONSTRAINT booking_expenses_cost_type_check
            CHECK (cost_type IN ('VENDOR', 'INTERNAL'));
    END IF;
END $$;

-- Serves the hot path: the INTERNAL-only SUM for one booking, run on every expense write and every
-- booking amount edit (BookingExpenseRepository.sumInternalCosts).
CREATE INDEX IF NOT EXISTS idx_bkexp_cost_type
    on booking_expenses (booking_id, cost_type, deleted_at);

-- ── 2. bookings.total_internal_costs ────────────────────────────────────────
-- Denormalised SUM of the booking's ACTIVE, INTERNAL-typed expense rows — the third term of
-- net_profit = customer_amount − vendor_cost − total_internal_costs. Stored rather than derived so
-- the six existing readers of net_profit keep reading one agreed column instead of each re-deriving
-- it (they already drifted once: DevDataSeeder invented a 30%-of-amount formula). BookingProfitService
-- is the only writer and recomputes both columns together from the ledger, never accumulating a
-- delta, so the pair can never disagree with the rows they summarise.
ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS total_internal_costs numeric(12,2) NOT NULL DEFAULT 0;

-- Booking is @Audited: Envers needs the column on the audit twin too, or every write to an audited
-- booking fails. No NOT NULL/DEFAULT here — _aud rows are historical snapshots and Envers writes
-- NULL for revisions recorded before the column existed.
ALTER TABLE bookings_aud
    ADD COLUMN IF NOT EXISTS total_internal_costs numeric(12,2);

-- ── 3. booking_cancellations.sunk_internal_costs ────────────────────────────
-- Frozen at cancel time alongside every other figure on the record, so the cancellation P&L stays
-- reproducible even if the expense ledger is edited afterwards. Sunk in FULL — unlike vendor cost
-- there is no recoverable counterpart, because the staff commission was earned and the gateway fee
-- was charged whether or not the customer travelled:
--
--     revised_net_profit = final_charge_base − sunk_vendor_cost − sunk_internal_costs
--
-- final_charge_base, not total_retained: gst_on_charge is output tax owed to the government and
-- tcs_retained is the customer's own tax credit. Neither is agency margin.
--
-- Nullable, matching every other money column on this table — rows written before this feature have
-- no value, and NULL correctly reads as "not recorded" rather than as a real zero.
ALTER TABLE booking_cancellations
    ADD COLUMN IF NOT EXISTS sunk_internal_costs numeric(12,2);

-- BookingCancellation is @Audited too.
ALTER TABLE booking_cancellations_aud
    ADD COLUMN IF NOT EXISTS sunk_internal_costs numeric(12,2);

-- ── 4. Index for agency revenue (Req #4) ────────────────────────────────────
-- agency_revenue = Σ customer_amount of active bookings + Σ final_charge_base of the period's
-- cancellations, keyed on cancel_date (the date the retention crystallises, not the original
-- booking date — that would attribute this period's forfeiture to a period already closed).
CREATE INDEX IF NOT EXISTS idx_bkcancel_tenant_date
    on booking_cancellations (tenant_id, cancel_date, deleted_at);


-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- PART 5 — Per-tenant tax configuration
-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- Same in-place-edit rationale as PARTS 2-4: V2 has never been stamped on the deployment database,
-- so no flyway_schema_history checksum can be invalidated. Every statement is idempotent.
--
-- WHY: every tax figure in the product was a PLATFORM-WIDE property. app.booking.gst-rate and
-- app.booking.tcs-rate stamped a flat 5% + 5% on every booking of every tenant — including purely
-- domestic ones, where TCS under s.206C(1G)/394 does not apply at all, so those tenants were
-- collecting a tax from their customers that the statute never imposed. The statutory slab
-- (app.accounting.tcs.*) and the TDS section rates (app.accounting.tds.*) were global too. None of
-- that is a platform decision: rates move with each Finance Act, and a tenant adopts the change when
-- their CA says so, not when this platform redeploys. So every rate moves onto the tenant's own
-- accounting_settings row, with the former global values as the STANDARD DEFAULTS they can override.
--
-- ZERO-REGRESSION GUARANTEE. Every column default equals the value the platform previously hardcoded
-- (booking GST 5%, booking TCS 5% applied ALWAYS, TCS slab 5%/20% either side of Rs 7,00,000, TDS
-- 2%/5%/10% with a 20% no-PAN floor), so on the instant this runs no tenant's tax changes by a
-- paisa. AccountingSettingsService additionally SEEDS a brand-new tenant's row from the legacy
-- properties, so an environment that had tuned them keeps its own values rather than the defaults.
--
-- tcs_applicability defaults to 'ALWAYS' for that reason alone. It is NOT the correct setting for a
-- domestic operator, and the settings screen says so — but silently changing what a customer is
-- charged during an upgrade would be worse than leaving a visible, documented choice.
--
-- RATES ARE STORED AS PERCENTS (5.00 = 5%), not fractions. That is what the tenant and their CA
-- read and edit; the calculators convert once at the boundary via accounting/support/Percents.

-- ── 1. Booking-level tax — the figures the customer is actually charged ──────
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS apply_gst_on_bookings boolean       NOT NULL DEFAULT true;
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS booking_gst_rate_pct  numeric(5,2)  NOT NULL DEFAULT 5.00;
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS tcs_applicability     varchar(20)   NOT NULL DEFAULT 'ALWAYS';
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS booking_tcs_rate_pct  numeric(5,2)  NOT NULL DEFAULT 5.00;

-- @Enumerated(STRING) ⇒ inline CHECK, and ddl-auto never ALTERs an existing one. Adding a fourth
-- applicability mode later means editing this constraint by hand or inserts fail at RUNTIME.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'accounting_settings_tcs_applicability_check'
    ) THEN
        ALTER TABLE accounting_settings
            ADD CONSTRAINT accounting_settings_tcs_applicability_check
            CHECK (tcs_applicability IN ('NEVER', 'OVERSEAS_ONLY', 'ALWAYS'));
    END IF;
END $$;

-- ── 2. Statutory TCS slab (the GST tax-invoice path) ────────────────────────
-- Defaults are the HISTORICAL 5%/20% either side of Rs 7,00,000. Note that from 1 Apr 2026 the law
-- is a flat 2% with NO threshold (s.394(1), Income-tax Act 2025) — the defaults deliberately do NOT
-- encode that, because changing a tenant's tax rate without their CA's sign-off is not this
-- migration's call. A tenant moves to the new regime by setting both rates to 2.00.
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS tcs_threshold      numeric(14,2) NOT NULL DEFAULT 700000.00;
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS tcs_rate_below_pct numeric(5,2)  NOT NULL DEFAULT 5.00;
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS tcs_rate_above_pct numeric(5,2)  NOT NULL DEFAULT 20.00;

-- ── 3. TDS withheld on vendor bills ─────────────────────────────────────────
-- s.206AA (no PAN ⇒ the HIGHER of the section rate and the no-PAN rate) stays hardcoded in
-- TdsCalculator: it is a statutory rule, not a rate, so it is not a tenant preference.
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS tds_194c_pct   numeric(5,2) NOT NULL DEFAULT 2.00;
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS tds_194h_pct   numeric(5,2) NOT NULL DEFAULT 5.00;
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS tds_194j_pct   numeric(5,2) NOT NULL DEFAULT 10.00;
ALTER TABLE accounting_settings
    ADD COLUMN IF NOT EXISTS tds_no_pan_pct numeric(5,2) NOT NULL DEFAULT 20.00;

-- ── 4. bookings.overseas_tour_package ───────────────────────────────────────
-- Needed for tcs_applicability = 'OVERSEAS_ONLY', the setting that actually matches the statute for
-- an agency selling both domestic and outbound. Per CBDT Circular 10/2023 a package qualifies only
-- if it bundles at least TWO of {international ticket, hotel, other similar expenditure} — a bare
-- international air ticket is not one — so this is an explicit judgement by the agent rather than
-- something inferred from the destination string.
--
-- Defaults false: an unclassified booking is treated as domestic, which under-collects rather than
-- over-collects. Over-collecting someone else's tax is the worse error, and the harder one to undo
-- once it has been remitted.
ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS overseas_tour_package boolean NOT NULL DEFAULT false;

-- Booking is @Audited — Envers needs the column on the audit twin or every write to an audited
-- booking fails. Nullable, no default: _aud rows are historical snapshots.
ALTER TABLE bookings_aud
    ADD COLUMN IF NOT EXISTS overseas_tour_package boolean;
