-- Quick Quote room planning and immutable quotation snapshots.
--
-- Additive and idempotent: existing leads/quotations remain valid, and every new field is nullable
-- except inside the two brand-new child tables. Hibernate runs with ddl-auto=validate, so this DDL
-- must be applied before deploying the matching entities.

-- Hotel Master selling rate used by the separate Quick Quote page.
ALTER TABLE IF EXISTS hotel_room_types
    ADD COLUMN IF NOT EXISTS base_rate numeric(15,2);

-- Optional room-wise planning on a lead. No row means the feature was not enabled; the aggregate
-- lead adults/children/infants/rooms fields remain the source of truth in that case.
CREATE TABLE IF NOT EXISTS lead_room_allocations (
    id                       bigint generated by default as identity,
    created_at               timestamp(6) not null,
    created_by               varchar(255),
    deleted_at               timestamp(6),
    deleted_by               varchar(255),
    public_id                uuid not null unique,
    updated_at               timestamp(6) not null,
    updated_by               varchar(255),
    lead_id                  bigint not null,
    room_number              integer not null,
    room_category_preference varchar(80),
    bed_preference           varchar(80),
    adults                   integer not null,
    children                 integer not null,
    infants                  integer not null,
    extra_beds               integer not null,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS lead_room_allocation_child_ages (
    room_allocation_id bigint not null,
    child_age          integer,
    age_order          integer not null,
    primary key (room_allocation_id, age_order)
);

CREATE INDEX IF NOT EXISTS idx_lead_room_allocation_lead
    ON lead_room_allocations (lead_id);

ALTER TABLE IF EXISTS lead_room_allocations
    DROP CONSTRAINT IF EXISTS fk_lead_room_allocation_lead;
ALTER TABLE IF EXISTS lead_room_allocations
    ADD CONSTRAINT fk_lead_room_allocation_lead
    FOREIGN KEY (lead_id) REFERENCES leads;

ALTER TABLE IF EXISTS lead_room_allocation_child_ages
    DROP CONSTRAINT IF EXISTS fk_lead_room_allocation_child_ages;
ALTER TABLE IF EXISTS lead_room_allocation_child_ages
    ADD CONSTRAINT fk_lead_room_allocation_child_ages
    FOREIGN KEY (room_allocation_id) REFERENCES lead_room_allocations;

-- One persisted quotation_hotel row is one room line in Quick Quote. The public IDs are logical
-- master links rather than FKs: issued quotations must survive a master rename/delete unchanged.
ALTER TABLE IF EXISTS quotation_hotels
    ADD COLUMN IF NOT EXISTS hotel_master_public_id uuid,
    ADD COLUMN IF NOT EXISTS room_type_master_public_id uuid,
    ADD COLUMN IF NOT EXISTS meal_plan_master_public_id uuid,
    ADD COLUMN IF NOT EXISTS bed_type varchar(100),
    ADD COLUMN IF NOT EXISTS room_occupancy integer,
    ADD COLUMN IF NOT EXISTS allocated_adults integer,
    ADD COLUMN IF NOT EXISTS allocated_children integer,
    ADD COLUMN IF NOT EXISTS allocated_infants integer,
    ADD COLUMN IF NOT EXISTS allocated_extra_beds integer,
    ADD COLUMN IF NOT EXISTS rate_source varchar(20);

CREATE TABLE IF NOT EXISTS quotation_hotel_child_ages (
    quotation_hotel_id bigint not null,
    child_age          integer,
    age_order          integer not null,
    primary key (quotation_hotel_id, age_order)
);

ALTER TABLE IF EXISTS quotation_hotel_child_ages
    DROP CONSTRAINT IF EXISTS fk_quotation_hotel_child_ages;
ALTER TABLE IF EXISTS quotation_hotel_child_ages
    ADD CONSTRAINT fk_quotation_hotel_child_ages
    FOREIGN KEY (quotation_hotel_id) REFERENCES quotation_hotels;
